apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: roboshop
  region: us-east-1

availabilityZones: ["us-east-1b", "us-east-1a"]
managedNodeGroups:
  - name: spot
    instancetype: m5.large
    desiredCapacity: 1
    spot: true