apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

availabilityZones: ["us-east-1a"]
managedNodeGroups:
  - name: spot
    instancetype: t3.medium
    desiredCapacity: 3
    spot: true